// Basic file generated by AI: https://chatgpt.com/share/6921fec2-7724-800c-920b-0850dc0d393a
import { OPENAI_API_MODEL, OPENAI_API_TEMPERATURE } from "../services/config/apiConfig.js";
import { db } from "../services/config/firebase.js";
import { getFunctions, httpsCallable } from "../services/config/firebaseSdk.js";
import { buildTrainingPrompt } from "../services/utils/promptBuilder.js";
import { getLiveInstructions } from "../services/models/dbService.js";
import { normalizeTrainingPlan } from "../services/utils/trainingPlan.js";

export async function generatePlan(userInput, oldPlan = null) {
    let liveInstructions = null;

    try {
        liveInstructions = await getLiveInstructions();
    } catch (error) {
        console.error("Critical: Failed to fetch live instructions.", error);
        throw new Error("Service temporarily unavailable. Could not load coaching instructions.");
    }

    const prompt = buildTrainingPrompt(userInput, oldPlan, liveInstructions);
    const instructionImageParts = Array.isArray(liveInstructions?.__images)
        ? liveInstructions.__images
            .filter((image) => image?.url)
            .map((image) => ({
                type: "image_url",
                image_url: { url: image.url }
            }))
        : [];

    const messages = [
        {
            role: "system",
            content: prompt
        }
    ];

    if (instructionImageParts.length > 0) {
        messages.push({
            role: "user",
            content: [
                {
                    type: "text",
                    text: "Use the attached instruction reference images as part of the coaching rules for this plan."
                },
                ...instructionImageParts
            ]
        });
    }

    const functions = getFunctions(db.app, "us-central1");
    const generateTrainingPlanCallable = httpsCallable(functions, "generateTrainingPlan");

    return generateTrainingPlanCallable({
        model: OPENAI_API_MODEL,
        temperature: OPENAI_API_TEMPERATURE,
        messages
    }).then((result) => {
        if (!result?.data?.success || !result?.data?.plan) {
            throw new Error("No training plan returned from the server.");
        }

        return normalizeTrainingPlan(result.data.plan);
    });
}
