// Basic file generated by AI: https://chatgpt.com/share/6921fec2-7724-800c-920b-0850dc0d393a
import {
    OPENAI_API_TEMPERATURE,
    OPENAI_PLAN_GENERATION_MODEL,
    OPENAI_PROGRAM_UPDATE_MODEL,
} from "../services/config/apiConfig.js";
import { db } from "../services/config/firebase.js";
import { getFunctions, httpsCallable } from "../services/config/firebaseSdk.js";
import {
    buildMissedSessionAdjustmentPrompt,
    buildTrainingPrompt,
} from "../services/utils/promptBuilder.js";
import {
    normalizeTrainingDay,
    parseGeneratedTrainingPlan,
} from "../services/utils/trainingPlan.js";

function normalizeGeneratedPlan(plan = {}) {
    return parseGeneratedTrainingPlan(plan);
}

async function getTrainingCallableResponse(messages = [], modelName = OPENAI_PLAN_GENERATION_MODEL) {
    const functions = getFunctions(db.app, "us-central1");
    const generateTrainingPlanCallable = httpsCallable(functions, "generateTrainingPlan");

    return generateTrainingPlanCallable({
        model: modelName,
        temperature: OPENAI_API_TEMPERATURE,
        messages
    }).then((result) => {
        if (!result?.data?.success || !result?.data?.plan) {
            throw new Error("No training plan returned from the server.");
        }

        return result.data.plan;
    });
}

export async function generatePlan(userInput, oldPlan = null) {
    const prompt = buildTrainingPrompt(userInput, oldPlan);
    const messages = [
        {
            role: "system",
            content: prompt
        }
    ];

    return getTrainingCallableResponse(
        messages,
        OPENAI_PLAN_GENERATION_MODEL
    ).then((plan) => normalizeGeneratedPlan(plan));
}

export async function adjustTrainingDayForMissedSession(adjustmentInput = {}) {
    const prompt = buildMissedSessionAdjustmentPrompt(adjustmentInput);
    const messages = [
        {
            role: "system",
            content: prompt
        }
    ];

    return getTrainingCallableResponse(
        messages,
        OPENAI_PROGRAM_UPDATE_MODEL
    ).then((day) =>
        normalizeTrainingDay(
            {
                ...day,
                day: adjustmentInput?.targetDay?.day || day?.day || 1,
                preferredWeekday:
                    adjustmentInput?.targetDay?.preferredWeekday ||
                    day?.preferredWeekday ||
                    "",
            },
            (adjustmentInput?.targetDay?.day || day?.day || 1) - 1
        )
    );
}
