// Basic file generated by AI: https://chatgpt.com/share/6921fec2-7724-800c-920b-0850dc0d393a
import { OPENAI_API_URL, OPENAI_API_MODEL, OPENAI_API_TEMPERATURE } from "../services/config/apiConfig.js";
import { buildTrainingPrompt } from "../services/utils/promptBuilder.js";
import { getApiConfig, getLiveInstructions } from "../services/models/dbService.js";

export async function generatePlan(userInput, oldPlan = null) {
    let apiKey = null;
    let liveInstructions = null;

    try {
        // Fetch secure config from Firestore and instruction files from Firebase Storage
        const [dbConfig, storageInstructions] = await Promise.all([
            getApiConfig(),
            getLiveInstructions()
        ]);

        // STRICT: We only accept the key from the Database
        if (dbConfig && dbConfig.openai_key) {
            apiKey = dbConfig.openai_key;
        } else {
            // If DB works but key is missing
            throw new Error("Configuration Error: No OpenAI API Key found in Firestore.");
        }

        if (storageInstructions) {
            liveInstructions = storageInstructions;
        }

    } catch (error) {
        // If the secure config fetch fails, we stop here because we have no API key.
        console.error("Critical: Failed to fetch API config or instructions.", error);
        throw new Error("Service temporarily unavailable. Could not retrieve security credentials.");
    }

    // Security Check
    if (!apiKey) {
        throw new Error("Authentication failed: Missing API Key.");
    }

    const prompt = buildTrainingPrompt(userInput, oldPlan, liveInstructions);
    const instructionImageParts = Array.isArray(liveInstructions?.__images)
        ? liveInstructions.__images
            .filter((image) => image?.url)
            .map((image) => ({
                type: "image_url",
                image_url: { url: image.url }
            }))
        : [];

    const messages = [
        {
            role: "system",
            content: prompt
        }
    ];

    if (instructionImageParts.length > 0) {
        messages.push({
            role: "user",
            content: [
                {
                    type: "text",
                    text: "Use the attached instruction reference images as part of the coaching rules for this plan."
                },
                ...instructionImageParts
            ]
        });
    }

    const payload = {
        model: OPENAI_API_MODEL,
        temperature: OPENAI_API_TEMPERATURE,
        messages,
        response_format: { type: "json_object" }
    };

    const options = {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(payload)
    };

    return fetch(OPENAI_API_URL, options)
        .then(response => response.json())
        .then(result => {
            if (result.error) {
                throw new Error(`OpenAI API Error: ${result.error.message}`);
            }
            const content = result?.choices?.[0]?.message?.content;
            if (!content) {
                throw new Error(`No content in API response: ${JSON.stringify(result)}`);
            }
            return JSON.parse(content);
        });
}
